<a href="https://colab.research.google.com/github/Chuck2Win/movie_recommendation_for_mom/blob/master/toy_project___collaborative_filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Collaborative filtering
- Memory Based
  - Item Based
  

This dataset (ml-latest-small) describes 5-star rating and free-text tagging activity from [MovieLens](http://movielens.org), a movie recommendation service. It contains 100836 ratings and 3683 tag applications across 9742 movies. These data were created by 610 users between March 29, 1996 and September 24, 2018. This dataset was generated on September 26, 2018.

In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import pandas as pd
from pandas import DataFrame as df
import nltk
from matplotlib import pyplot as plt
from google.colab import drive
import os
drive.mount('/content/gdrive')
print(os.getcwd()) # current working directory 확인


Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive
/content


In [2]:
os.chdir('./gdrive/My Drive')
os.mkdir('./Recomendation_toy')
os.chdir('/Recomendation_toy')

FileNotFoundError: ignored

In [0]:
os.mkdir('./toy_movie_recommendation')
os.chdir('./toy_movie_recommendation')

In [8]:
os.getcwd()

'/content/gdrive/My Drive/toy_movie_recommendation'

In [13]:
# file uplaod
from google.colab import files
uploaded=files.upload()

Saving movies.csv to movies.csv


In [12]:
ratings=pd.read_csv('./ratings.csv',header=0)
ratings.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [28]:
print(len(set(ratings['userId']))) # 610
print(len(set(ratings['movieId']))) # 9724
user_id_dict={original:new for new,original in enumerate(set(ratings['userId']))}
movie_id_dict={original:new for new,original in enumerate(set(ratings['movieId']))}

610
9724


In [33]:
# matrix 구성
# 행은 id, 열은 movie
matrix=np.zeros((610,9724))
for i in set(ratings['userId']):
    a=user_id_dict[i]
    b=movie_id_dict[ratings.loc[a,'movieId']]
    matrix[a,b]=ratings.loc[a,'rating']
    # =ratings.loc[i.'ratings']
print(matrix)

[[4. 0. 0. ... 0. 0. 0.]
 [0. 0. 4. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [34]:
matrix.shape

(610, 9724)

In [0]:
from sklearn.metrics.pairwise import cosine_similarity

In [0]:
# collaborative filtering - memory based - item based
Matrix=cosine_similarity(matrix.T,matrix.T)

In [38]:
# usual suspect와 비슷한 것
# movie id 50
index_movie_id={value:key for key,value in movie_id_dict.items()}
index_movie_id[50] # usual suspect

49

In [48]:
# 근데 나는 지금 엄마는 정보가 없으니깐 content based로 가야되니깐 결국 cosine similarity로..
index_movie_id[Matrix[index_movie_id[50]].argsort()[-2]] # Deadfall_2012

98296